all:
  children:
    campus1:
      hosts:
        lab-sw-01:
          ansible_host: 10.50.0.4
          MPID: 1
  vars:
    ansible_network_os: eos
    ansible_connection: network_cli
    ansible_user: admin
